FROM node:24

WORKDIR /data/client

COPY package*.json ./
RUN npm install

COPY . .

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

RUN npm run build

EXPOSE ${CLIENT_PORT}
CMD ["npm", "run", "preview"]