services:
  # client:
  #   build: ./frontend
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - mikemaniax-cli:/data
  #   working_dir: /data/frontend
  
  backend:
    build: ./backend
    env_file:
      - stack.env
    ports:
      - "8080:${PORT}"
    volumes:
      - mikemaniax-api:/data
    # working_dir: /data/backend

volumes:
  # mikemaniax-cli:
  mikemaniax-api: