services:
  mikemaniax:
    build: ./mikemaniax
    env_file:
      - "./mikemaniax/.env"
    ports:
      - "8080:${PORT}"
    volumes:
      - mikemaniax:/app
    working_dir: /app

volumes:
  mikemaniax: