FROM node:24

WORKDIR /data/api

COPY package*.json ./
RUN npm install

COPY . .

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

RUN npm run build

EXPOSE ${API_PORT}
CMD ["npm", "start"]